# The URL the site will be built for
base_url = "/la-ramure-des-mots"
title = "La ramure des mots"
compile_sass = true
minify_html = false
build_search_index = false

theme = "roots"

[markdown]
highlight_code = false

[extra]
theme_logo_path = "tree-alt.svg"
theme_extra_menu = []
theme_exclude_menu = ["Mentions légales"]
